spring:
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  datasource:
    url: jdbc:mysql://localhost:3306/soleador_db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
      hibernate.format_sql: true
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
server:
  error:
    whitelabel:
      enabled: true
  port: 8080